version: '3.4'

services:
  php:
    build:
      context: .
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app:rw,cached

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_USER=postgresql
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 8642
        protocol: tcp
  nginx:
    container_name: nginx_app
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/app:rw,cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

volumes:
  db-data: {}
